var ProductList = [
    {
        pid: 1,
        title: 'Apple iPhone 11',
        category: 'Telefon',
        descShort: 'Mobilní telefon 6,1" IPS 1792 × 828, procesor Apple A13 Bionic 6jádrový, RAM 4 GB, interní paměť 64 GB, zadní fotoaparát s optickým zoomem 12 Mpx (f/1,8) + 12 Mpx (f/2,4), přední fotoaparát 12 Mpx, optická stabilizace, GPS, Glonass, NFC, LTE',
        price: 18490,
        description: 'Mobilní telefon 6,1" IPS 1792 × 828, procesor Apple A13 Bionic 6jádrový, RAM 4 GB, interní paměť 64 GB, zadní fotoaparát s optickým zoomem 12 Mpx (f/1,8) + 12 Mpx (f/2,4), přední fotoaparát 12 Mpx, optická stabilizace, GPS, Glonass, NFC, LTE, UWB, Lightning port, voděodolný dle IP68, single SIM + eSIM, neblokovaný, rychlé nabíjení 18W, bezdrátové nabíjení, baterie 3110 mAh, iOS 13',
        image: 'iphone-11.jpg',
      },
      {
        pid: 2,
        title: 'Apple iPhone 12',
        category: 'Telefon',
        descShort: 'Mobilní telefon 6,1" OLED 2532 × 1170, procesor Apple A14 Bionic 6jádrový, interní paměť 128 GB, zadní fotoaparát 12 Mpx (f/1,6) + 12 Mpx (f/2,4), přední fotoaparát 12 Mpx, optická stabilizace, GPS, Glonass, NFC, LTE, 5G',
        price: 26490,
        description: 'Mobilní telefon 6,1" OLED 2532 × 1170, procesor Apple A14 Bionic 6jádrový, interní paměť 128 GB, zadní fotoaparát 12 Mpx (f/1,6) + 12 Mpx (f/2,4), přední fotoaparát 12 Mpx, optická stabilizace, GPS, Glonass, NFC, LTE, 5G, Lightning port, voděodolný dle IP68, single SIM + eSIM, neblokovaný, rychlé nabíjení 20W, bezdrátové nabíjení 15W, baterie 2815 mAh, iOS 14. Nový iPhone 12 je vybavený 6,1" Super Retina XDR displejem, který nabízí jemné rozlišení 2 532 × 1 170 bodů s jemností 460 pixelů na palec. Mezi jeho klíčové benefity patří podpora HDR 10 a Dolby Vison, maximální jas 625 nitů (v HDR až 1 200) nebo ohromný kontrastní poměr 2 000 000:1. Celou čelní stranu pak kryje speciálně vyvinuté sklo zvané Ceramic Shield. Apple slibuje zhruba 4násobnou odolnost proti pádu.  Pro telefon iPhone 12 si Apple připravil duální fotoaparát s vylepšenou optikou. Hlavní širokoúhlý objektiv se pyšní světelností f/1,6, optickou stabilizací obrazu i sedmičlenným objektivem. Ultraširokoúhlý fotoaparát pak disponuje clonou f/2,4 a 120° zorným polem. Nárůst kvality snímků je znatelný i za sníženého osvětlení. Nová kamera totiž zachytí o 27 % více světla. To platí i pro natáčení videí. A mimochodem, jde o první řadu iPhonů s podporou záznamu videa ve filmové kvalitě Dolby Vision.  Velkou revolucí je integrovaná podpora 5G, pro kterou Apple využívá svůj vlastní čip s nízkou spotřebou energie. Díky tomu má technologii plně pod kontrolou. Zajímavostí je funkce Smart Data Mode s automatickým přepínáním mezi vhodnými sítěmi.',
        image: 'iphone-12.jpeg',
      },
      {
        pid: 3,
        title: 'Motorola Moto G9 Plus',
        category: 'Telefon',
        descShort: 'Mobilní telefon 6,8" IPS 2340 × 1080, 8jádrový procesor, RAM 4 GB, interní paměť 128 GB, Micro SD až 512 GB, zadní fotoaparát 64 Mpx (f/1,8) + 8 Mpx (f/2,2) + 2 Mpx (f/2,2) + 2 Mpx (f/2,2), přední fotoaparát 16 Mpx, elektronická stabilizace, GPS, Glonass, NFC, LTE',
        price: 5499,
        description: 'Mobilní telefon 6,8" IPS 2340 × 1080, 8jádrový procesor, RAM 4 GB, interní paměť 128 GB, Micro SD až 512 GB, zadní fotoaparát 64 Mpx (f/1,8) + 8 Mpx (f/2,2) + 2 Mpx (f/2,2) + 2 Mpx (f/2,2), přední fotoaparát 16 Mpx, elektronická stabilizace, GPS, Glonass, NFC, LTE, Jack (3,5mm) a USB-C, čtečka otisků, hybridní slot, neblokovaný, baterie 5000 mAh, Android 10. Pokud rádi sledujete na mobilu oblíbené seriály nebo filmy, pak je Moto G9 Plus skvělá volba. Displej s úhlopříčkou 6,8" disponuje rozlišením 2 400 × 1 080 bodů a IPS technologií pro zobrazení živých barev s kvalitním zobrazením bez zkreslení i při pohledu ze širokých úhlů. Navíc je displej opatřen certifikací pro zobrazení obsahu v HDR. Díky poměru stran 20:9 je Motorola Moto G9 Plus skvělým telefonem pro hraní her nebo sledování videí.  Telefon Motorola Moto G9 Plus nabídne povedený vzhled i bohatou výbavu s dlouhou výdrží baterie. O dostatek výkonu se postará 8jádrový procesor se 4 GB RAM pro efektivní práci s aplikacemi. Pohodlné odemykání telefonu Motorola Moto G9 Plus je pak vyřešeno pomocí čtečky otisků prstů nebo funkcí pro odemykání obličejem.',
        image: 'motorola-g9-plus.jpg',
      },
      {
        pid: 4,
        title: 'Acer Nitro 5 Obsidian Black',
        category: 'Laptop',
        descShort: 'Herní notebook - Intel Core i5 10300H Comet Lake, 15.6" IPS matný 1920 × 1080 144Hz, RAM 16GB DDR4, NVIDIA GeForce RTX 2060 6GB, SSD 1000GB, podsvícená klávesnice, USB 3.2 Gen 1, USB-C, WiFi 6',
        price: 31990,
        description: 'Objevte a vychutnejte si novou úroveň hraní s výkonným Nitro 5. Tento robustní notebook s decentním designem je vybaven 144Hz Full HD IPS displejem a celou řadou působivých technologií vylepšujících každý aspekt hraní.  Ovládněte herní svět díky kombinovanému výkonu procesoru Intel Core i5 10300H Comet Lake a NVIDIA GeForce RTX 2060 6GB. Prozkoumávejte hry ve větších detailech díky ostrému obrazu na 15,6" Full HD IPS displeji. Vychutnejte si na notebooku Acer Nitro 5 plynulé hraní bez rozmazání díky obnovovací frekvenci až 144 Hz a 3ms době odezvy.  Pokud vyžaduje náročné využívání vyšší výkon, notebook Acer Nitro 5 jej hravě zvládne díky dvěma ventilátorům a konstrukci se čtyřmi výdechy teplého vzduchu.',
        image: 'acer-nitro-5.jpg',
      },
      {
        pid: 5,
        title: 'HP EliteBook 845 G7',
        category: 'Laptop',
        descShort: 'Notebook - AMD Ryzen 3 PRO 4450U, 14" IPS matný 1920 × 1080, RAM 8GB DDR4, AMD Radeon Vega 5, SSD 256GB, podsvícená klávesnice, webkamera, USB 3.2 Gen 1, USB-C, čtečka otisků prstů, WiFi 6, 53 Wh baterie, Windows 10 Pro',
        price: 24990,
        description: 'S výkonným, bezpečným a odolným notebookem HP EliteBook 845 G7 budete produktivní v každé situaci po celý den. Tenký a lehký 14palcový notebook snadno přenesete kamkoliv vás vaše pracovní povinnosti zavedou. Vyniká precizním řemeslným zpracováním celokovového šasi ve stříbrném provedení. O skvělý výpočetní výkon notebooku HP EliteBook 845 G7 se postará čtyřjádrový procesor AMD Ryzen 3 4. generace spolu. Rychlý start systému a krátké vybavovací doby pro vaše data zajistí SSD úložiště o kapacitě 256 GB. Práci na HP EliteBook 845 G7 vám zpříjemní špičkový displej s úhlopříčkou 14" ve Full HD rozlišení s antireflexní úpravou. Díky tenkým rámečkům je dosaženo 85% poměru obrazovky k tělu. Na nové klávesnici a touchpadu s podporou vícedotykových gest se pracuje tiše a pohodlně.  Na notebooku HP EliteBook 845 G7 určitě oceníte pokročilé videokonferenční řešení s HD webkamerou vybavenou HP Privacy fyzickou závěrkou. Vysoce kvalitní zvuk dodají dva reproduktorů Bang & Olufsen. Pro bezdrátovou komunikaci jsou v notebooku HP EliteBook 845 G7 k dispozici WiFi 6 a Bluetooth 5.0. V konektorové výbavě naleznete porty USB 3.2 včetně UCB-C s podporou napájení, HDMI výstup, čtečka čipových karet a slot pro SIM kartu.',
        image: 'hp-elitebook-645-g7.jpg',
      },
      {
        pid: 6,
        title: 'Lenovo IdeaCentre G5',
        category: 'Stolní počítač',
        descShort: ' Herní PC Intel Core i5 10400F Comet Lake 4.3 GHz, NVIDIA GeForce GTX 1660 Super 6GB, RAM 16GB DDR4, SSD 1000 GB, Bez mechaniky, HDMI a DisplayPort, 2× USB 3.2, 4× USB 2.0, Windows 10 Home',
        price: 24990,
        description: 'Počítač Lenovo IdeaCentre G5 je navržený pro domácí zábavu a hry. Jedná se o stolní počítač pro multimediální použití v domácnosti, který zvládá i herní nasazení, takže ho plně využije celá rodina. Pořiďte si výkon v elegantním provedení značkového výrobce.  Počítače IdeaCentre G5 14IMB05 jsou postaveny na moderních procesorech Intel Core 10. generace v kombinaci s využitím interní grafiky Intel UHD Graphics nebo herních grafických akcelerátorů NVIDIA GeForce GTX/RTX a AMD Radeon RX (v závislosti na konfiguraci modelu). Vysoký výkon ještě dokresluje použitá operační paměť DDR4 a možnost osazení SSD pevného disku nebo využití technologie Intel Optane Memory.  Dopřejte si dokonalý audiovizuální zážitek s počítačem IdeaCentre G5, který se může pochlubit kvalitním zvukovým podáním HD Audio. S multimediálním rozhraním HDMI vám nabídne přenos obrazu a zvuku ve vysoké digitální kvalitě.  Počítač Lenovo G5 14IMB05 se vyznačuje perfektními akustickými vlastnostmi díky promyšlené koncepci chlazení, která snižuje hladinu hlučnosti při plném zatížení procesoru. Má také vestavěný senzor chytrého chlazení, který rozpozná okolní teplotu a automaticky přizpůsobí úroveň chlazení. Počítač je tak méně hlučný a vy můžete v klidu pracovat bez rozptylování z hučení.',
        image: 'lenovo-ideacentre-g5.jpg',
      },
      {
        pid: 7,
        title: 'Raspberry Pi 4 Model B',
        category: 'Ostatní',
        descShort: '4GB RAM - Varianta již čtvrté generace nejoblíbenějšího jednodeskového počítače na světě.',
        price: 1599,
        description: 'Revize 1.2. Raspberry Pi je nejoblíbenější jednodeskový počítač na světě. První model přišel v roce 2012 se skromným cílem - posílit technické vzdělávání dětí - a odstartoval malou průmyslovou revoluci. Raspberry Pi 4 Model B je dosud nejvýkonnější model a první plnohodnotná náhrada PC!  Základním stavebním kamenem Raspberry Pi 4B je jeho 1.5GHz čtyřjádrový procesor ARM Cortex-A72. Přechod na modernější 28nm technologii umožnil Raspberry Pi 4B dosáhnout významného zvýšení výkonu procesoru, multimédií a I/O, díky čemuž je nyní plnohodnotným osobním počítačem. Grafika VideoCore byla povýšena na verzi VI. Přináší 4Kp60 video, dekódování HEVC/H.265 a režim dvou monitorů!  Varianta: Raspberry Pi 4 Model B - 4GB RAM',
        image: 'rpi-model4.jpg',
      },
];

export default ProductList;
